//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALERTAS
    {
        public decimal ID { get; set; }
        public Nullable<decimal> PAC_ID { get; set; }
        public Nullable<decimal> RES_ID { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    
        public virtual PACIENTES PACIENTES { get; set; }
        public virtual RESERVAS RESERVAS { get; set; }
    }
}
