//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_RECETA
    {
        public decimal ID { get; set; }
        public Nullable<decimal> FOR_ID { get; set; }
        public Nullable<decimal> MED_ID { get; set; }
        public Nullable<decimal> ENT_ID { get; set; }
        public Nullable<decimal> EST_ID { get; set; }
        public Nullable<decimal> DOSIS { get; set; }
        public Nullable<decimal> DIAS { get; set; }
        public Nullable<decimal> LAPSO { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
    
        public virtual ENTREGAS ENTREGAS { get; set; }
        public virtual ESTADOS_DETALLE ESTADOS_DETALLE { get; set; }
        public virtual FORMULARIO FORMULARIO { get; set; }
        public virtual MEDICAMENTOS MEDICAMENTOS { get; set; }
    }
}
