//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICAMENTOS
    {
        public MEDICAMENTOS()
        {
            this.DETALLE_RECETA = new HashSet<DETALLE_RECETA>();
            this.ELIMINACIONES = new HashSet<ELIMINACIONES>();
            this.INGRESOS = new HashSet<INGRESOS>();
            this.PARTIDAS = new HashSet<PARTIDAS>();
            this.RESERVAS = new HashSet<RESERVAS>();
        }
    
        public decimal ID { get; set; }
        public Nullable<decimal> LAB_ID { get; set; }
        public Nullable<decimal> FOR_ID { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<decimal> CONTENIDO { get; set; }
        public Nullable<decimal> GRAMAJE { get; set; }
        public Nullable<decimal> STOCK { get; set; }
        public string COMPONENTES { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<DETALLE_RECETA> DETALLE_RECETA { get; set; }
        public virtual ICollection<ELIMINACIONES> ELIMINACIONES { get; set; }
        public virtual FORMATOS FORMATOS { get; set; }
        public virtual ICollection<INGRESOS> INGRESOS { get; set; }
        public virtual LABORATORIOS LABORATORIOS { get; set; }
        public virtual ICollection<PARTIDAS> PARTIDAS { get; set; }
        public virtual ICollection<RESERVAS> RESERVAS { get; set; }
    }
}
