//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entidades : DbContext
    {
        public Entidades()
            : base("name=Entidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ALERTAS> ALERTAS { get; set; }
        public DbSet<DETALLE_RECETA> DETALLE_RECETA { get; set; }
        public DbSet<ELIMINACIONES> ELIMINACIONES { get; set; }
        public DbSet<ENTREGAS> ENTREGAS { get; set; }
        public DbSet<ESTADOS_DETALLE> ESTADOS_DETALLE { get; set; }
        public DbSet<FORMATOS> FORMATOS { get; set; }
        public DbSet<FORMULARIO> FORMULARIO { get; set; }
        public DbSet<INGRESOS> INGRESOS { get; set; }
        public DbSet<LABORATORIOS> LABORATORIOS { get; set; }
        public DbSet<MEDICAMENTOS> MEDICAMENTOS { get; set; }
        public DbSet<MOTIVO_ELIMINACION> MOTIVO_ELIMINACION { get; set; }
        public DbSet<PACIENTES> PACIENTES { get; set; }
        public DbSet<PACIENTES_TUTORES> PACIENTES_TUTORES { get; set; }
        public DbSet<PARTIDAS> PARTIDAS { get; set; }
        public DbSet<RESERVAS> RESERVAS { get; set; }
        public DbSet<TIPOS_USUARIOS> TIPOS_USUARIOS { get; set; }
        public DbSet<TUTORES> TUTORES { get; set; }
        public DbSet<USUARIOS> USUARIOS { get; set; }
    }
}
