//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTES
    {
        public PACIENTES()
        {
            this.ALERTAS = new HashSet<ALERTAS>();
            this.ENTREGAS = new HashSet<ENTREGAS>();
            this.FORMULARIO = new HashSet<FORMULARIO>();
            this.PACIENTES_TUTORES = new HashSet<PACIENTES_TUTORES>();
            this.RESERVAS = new HashSet<RESERVAS>();
        }
    
        public decimal ID { get; set; }
        public string RUT { get; set; }
        public string NOMBRE { get; set; }
        public string DIRECCION { get; set; }
        public string COMUNA { get; set; }
        public Nullable<System.DateTime> NACIMIENTO { get; set; }
        public Nullable<decimal> TELEFONO { get; set; }
        public string EMAIL { get; set; }
    
        public virtual ICollection<ALERTAS> ALERTAS { get; set; }
        public virtual ICollection<ENTREGAS> ENTREGAS { get; set; }
        public virtual ICollection<FORMULARIO> FORMULARIO { get; set; }
        public virtual ICollection<PACIENTES_TUTORES> PACIENTES_TUTORES { get; set; }
        public virtual ICollection<RESERVAS> RESERVAS { get; set; }
    }
}
