//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTIDAS
    {
        public PARTIDAS()
        {
            this.ELIMINACIONES = new HashSet<ELIMINACIONES>();
            this.INGRESOS = new HashSet<INGRESOS>();
        }
    
        public decimal ID { get; set; }
        public Nullable<decimal> MED_ID { get; set; }
        public Nullable<System.DateTime> FECHA_ELAB { get; set; }
        public Nullable<System.DateTime> FECHA_VENC { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<decimal> CANTIDAD { get; set; }
    
        public virtual ICollection<ELIMINACIONES> ELIMINACIONES { get; set; }
        public virtual ICollection<INGRESOS> INGRESOS { get; set; }
        public virtual MEDICAMENTOS MEDICAMENTOS { get; set; }
    }
}
