//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOS_USUARIOS
    {
        public TIPOS_USUARIOS()
        {
            this.USUARIOS = new HashSet<USUARIOS>();
        }
    
        public decimal ID { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
    }
}
