//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public USUARIOS()
        {
            this.ELIMINACIONES = new HashSet<ELIMINACIONES>();
            this.ENTREGAS = new HashSet<ENTREGAS>();
            this.FORMULARIO = new HashSet<FORMULARIO>();
            this.INGRESOS = new HashSet<INGRESOS>();
            this.RESERVAS = new HashSet<RESERVAS>();
        }
    
        public decimal ID { get; set; }
        public Nullable<decimal> TIP_ID { get; set; }
        public string RUT { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<decimal> TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public string PASS { get; set; }
        public Nullable<decimal> ESTADO { get; set; }
    
        public virtual ICollection<ELIMINACIONES> ELIMINACIONES { get; set; }
        public virtual ICollection<ENTREGAS> ENTREGAS { get; set; }
        public virtual ICollection<FORMULARIO> FORMULARIO { get; set; }
        public virtual ICollection<INGRESOS> INGRESOS { get; set; }
        public virtual ICollection<RESERVAS> RESERVAS { get; set; }
        public virtual TIPOS_USUARIOS TIPOS_USUARIOS { get; set; }
    }
}
