//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADOS_DETALLE
    {
        public ESTADOS_DETALLE()
        {
            this.DETALLE_RECETA = new HashSet<DETALLE_RECETA>();
        }
    
        public decimal ID { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<DETALLE_RECETA> DETALLE_RECETA { get; set; }
    }
}
