//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos2
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMULARIO
    {
        public FORMULARIO()
        {
            this.DETALLE_RECETA = new HashSet<DETALLE_RECETA>();
        }
    
        public decimal ID { get; set; }
        public Nullable<decimal> USU_ID { get; set; }
        public Nullable<decimal> PAC_ID { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
    
        public virtual ICollection<DETALLE_RECETA> DETALLE_RECETA { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
        public virtual PACIENTES PACIENTES { get; set; }
    }
}
