//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTES_TUTORES
    {
        public decimal ID { get; set; }
        public Nullable<decimal> TUT_ID { get; set; }
        public Nullable<decimal> PAC_ID { get; set; }
        public string PARENTESCO { get; set; }
    
        public virtual PACIENTES PACIENTES { get; set; }
        public virtual TUTORES TUTORES { get; set; }
    }
}
